language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

matrix:
  fast_finish: true
  include:
    # Minimum supported dependencies with the latest and oldest PHP version
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

      # Test the latest stable release
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
    - php: 8.0

      # Test LTS versions. This makes sure we do not use Symfony packages with version greater than 4.4.
    - php: 7.4
      env:
        - DEPENDENCIES="symfony/flex"
        - LTS_CONFIG="4.4.*"

      # Latest commit to master
    - php: 7.4
      env: STABILITY="dev"
    - php: 8.0
      env: STABILITY="dev"

  allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -z "$LTS_CONFIG" ]; then composer config extra.symfony.require ${LTS_CONFIG}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
  - ./vendor/bin/simple-phpunit install

script:
  - composer validate --strict --no-check-lock
  # simple-phpunit is the PHPUnit wrapper provided by the PHPUnit Bridge component and
  # it helps with testing legacy code and deprecations (composer require symfony/phpunit-bridge)
  - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS