# This file is part of the Jblab PasswordValidatorBundle package.
# Copyright (c) 2023-2025 Jblab <https://jblab.io/>
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
services:
  php:
    build:
      context: .
    volumes:
      - .:/app
    command:
      - sleep
      - infinity